---
title: "STAT 184 Homework Exercises" 
subtitle: "DataComputing Chapters 5 & 6"
author: "Ming Wang"
output: html_notebook
---

## Assigned Exercises

- DC Chapter 1 Exercises: 1.1, 1.2, 1.3, 1.4, 1.5  
- DC Chapter 2 Exercises: 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.8, 2.9

## Front Matter

```{r}
# clean up workspace environment
rm(list = ls())

# all packages used for the assignment
library(mosaic) #myplot()
library(tidyverse) #ggplot2
library(esquisse) #esquisser()
library(tidytuesdayR)


#data intake
TuesData<-tidytuesdayR::tt_load(2020,week = 52)
BigMac<-TuesData[["big-mac"]]

```
#Big Mac plot
```{r}
ggplot(BigMac) +
 aes(x = dollar_price) +
 geom_histogram(bins = 30L, fill = "#0c4c8a") +
 theme_minimal()
```

#Big Mac Plot
```{r}
ggplot(BigMac) +
 aes(x = dollar_price, y = gbp_raw) +
 geom_point(size = 1L, colour = "#0c4c8a") +
 theme_minimal()
```
## Chapter 5 Exercises

### Problem 5.1
# access`CPS85`data set from`mosaicData`packagedata
```{r}
data("CPS85", package = "mosaicData")
esquisser(CPS85)
```
```{r}
ggplot(CPS85) +
 aes(x = sex, y = wage, fill = exper, colour = married) +
 geom_boxplot() +
 scale_fill_gradient() +
 scale_color_hue() +
 theme_bw() +
 facet_wrap(vars(race))
```

### Problem 5.2
# access`NCHS`data set from`dcData`packagedata
```{r}
data("NCHS", package = "dcData")
esquisser(NCHS)
```
```{r}
ggplot(NCHS) +
 aes(x = bmi, fill = chol, colour = sex) +
 geom_density(adjust = 1L) +
 scale_fill_gradient() +
 scale_color_hue() +
 theme_bw() +
 facet_wrap(vars(pregnant))
```

[and so forth...]



### Problem 5.3
# access`CPS85`data set from`mosaicData`packagedata
```{r}
data("CPS85", package = "mosaicData")
esquisser(CPS85)
```
```{r}
ggplot(CPS85) +
 aes(x = exper, y = wage, colour = married) +
 geom_point(size = 1L) +
 scale_color_hue() +
 theme_bw() +
 facet_wrap(vars(sector))
```
[and so forth...]

